from __future__ import annotations

import json
import os
import smtplib
from dataclasses import dataclass
from email.mime.text import MIMEText
from pathlib import Path
from typing import Iterable
from urllib.request import Request, urlopen

import pandas as pd

from ..env_loader import load_project_env


@dataclass
class EmailDispatchConfig:
    provider: str = "smtp"
    send_emails: bool = False
    notification_email: str = ""


def _clean(value: str) -> str:
    return (value or "").strip()


def _build_subject(role: str, company: str) -> str:
    role_clean = _clean(role) or "Open Role"
    company_clean = _clean(company) or "Client"
    return f"Shortlist Update: {role_clean} - {company_clean}"


def _build_body(row_num: int, role: str, company: str, candidates: Iterable[dict]) -> str:
    lines = [
        "Recruiter shortlist generated by Hiring Pipeline",
        "",
        f"Job Row: {row_num}",
        f"Role: {_clean(role)}",
        f"Company: {_clean(company)}",
        "",
        "Top matched candidates:",
    ]

    candidate_rows = list(candidates)
    if not candidate_rows:
        lines.append("- No candidates met the matching threshold.")
    else:
        for candidate in candidate_rows:
            lines.append(
                "- {name} | score={score} | skills={skills} | notice={notice}".format(
                    name=_clean(str(candidate.get("candidate_name", ""))),
                    score=str(candidate.get("match_score", "")),
                    skills=_clean(str(candidate.get("candidate_skills", ""))),
                    notice=_clean(str(candidate.get("notice_period_days", ""))),
                )
            )

    return "\n".join(lines)


def _smtp_send(recipient: str, subject: str, body: str) -> tuple[bool, str]:
    server = os.getenv("SMTP_SERVER", "smtp.gmail.com")
    port = int(os.getenv("SMTP_PORT", "587"))
    sender = _clean(os.getenv("SENDER_EMAIL", ""))
    password = _clean(os.getenv("SENDER_PASSWORD", "")).replace(" ", "")

    if not sender or not password:
        return False, "Missing SMTP credentials (SENDER_EMAIL/SENDER_PASSWORD)"

    msg = MIMEText(body)
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = recipient

    try:
        if port == 465:
            with smtplib.SMTP_SSL(server, port, timeout=30) as client:
                client.login(sender, password)
                client.sendmail(sender, [recipient], msg.as_string())
        else:
            with smtplib.SMTP(server, port, timeout=30) as client:
                client.ehlo()
                if port == 587:
                    client.starttls()
                    client.ehlo()
                client.login(sender, password)
                client.sendmail(sender, [recipient], msg.as_string())
        return True, "Email sent via SMTP"
    except Exception as exc:
        return False, f"SMTP send failed: {exc}"


def _sendgrid_send(recipient: str, subject: str, body: str) -> tuple[bool, str]:
    api_key = _clean(os.getenv("SENDGRID_API_KEY", ""))
    sender = _clean(os.getenv("SENDGRID_SENDER_EMAIL", os.getenv("SENDER_EMAIL", "")))
    if not api_key or not sender:
        return False, "Missing SendGrid configuration (SENDGRID_API_KEY/SENDGRID_SENDER_EMAIL)"

    payload = {
        "personalizations": [{"to": [{"email": recipient}]}],
        "from": {"email": sender},
        "subject": subject,
        "content": [{"type": "text/plain", "value": body}],
    }

    request = Request(
        "https://api.sendgrid.com/v3/mail/send",
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )

    try:
        with urlopen(request, timeout=30) as response:
            status = getattr(response, "status", 202)
            if 200 <= status < 300:
                return True, "Email sent via SendGrid"
            return False, f"SendGrid responded with status {status}"
    except Exception as exc:
        return False, f"SendGrid send failed: {exc}"


def dispatch_shortlist_emails(
    matches_df: pd.DataFrame,
    jd_catalog_df: pd.DataFrame,
    output_file: Path,
    config: EmailDispatchConfig,
) -> pd.DataFrame:
    load_project_env(Path(__file__).resolve().parents[2])
    output_file.parent.mkdir(parents=True, exist_ok=True)

    recipient = _clean(config.notification_email) or _clean(os.getenv("PIPELINE_NOTIFICATION_EMAIL", ""))
    if not recipient:
        recipient = _clean(os.getenv("DEFAULT_FALLBACK_RECIPIENT", ""))

    dispatch_rows: list[dict] = []

    for _, jd in jd_catalog_df.iterrows():
        row_num = int(jd.get("row_num", 0))
        role = str(jd.get("role", ""))
        company = str(jd.get("company", ""))

        candidates = []
        if not matches_df.empty:
            candidates = matches_df[matches_df["row_num"] == row_num].head(5).to_dict("records")

        subject = _build_subject(role, company)
        body = _build_body(row_num, role, company, candidates)

        if not recipient:
            dispatch_rows.append(
                {
                    "row_num": row_num,
                    "provider": config.provider,
                    "recipient": "",
                    "status": "skipped",
                    "message": "No notification recipient configured",
                    "subject": subject,
                }
            )
            continue

        if not config.send_emails:
            dispatch_rows.append(
                {
                    "row_num": row_num,
                    "provider": config.provider,
                    "recipient": recipient,
                    "status": "dry-run",
                    "message": "Email generation only (send disabled)",
                    "subject": subject,
                }
            )
            continue

        provider = config.provider.lower().strip()
        if provider == "sendgrid":
            success, message = _sendgrid_send(recipient, subject, body)
        else:
            success, message = _smtp_send(recipient, subject, body)

        dispatch_rows.append(
            {
                "row_num": row_num,
                "provider": provider,
                "recipient": recipient,
                "status": "sent" if success else "failed",
                "message": message,
                "subject": subject,
            }
        )

    dispatch_df = pd.DataFrame(
        dispatch_rows,
        columns=["row_num", "provider", "recipient", "status", "message", "subject"],
    )
    dispatch_df.to_csv(output_file, index=False)
    return dispatch_df
